-- Honor.gg — Supabase Schema
-- Run this in the Supabase SQL Editor

create table if not exists public.tier_entries (
  id           bigint primary key generated always as identity,
  spec_id      text not null,
  content_type text not null check (content_type in ('mythic_plus', 'raid', 'pvp')),
  rank         text not null check (rank in ('S', 'A', 'B', 'C', 'D')),
  score        integer not null check (score between 0 and 100),
  notes        text,
  patch        text not null default '12.0.5',
  updated_at   timestamptz not null default now(),
  unique (spec_id, content_type)
);

-- Enable Row Level Security (read-only public access)
alter table public.tier_entries enable row level security;

create policy "Public read access"
  on public.tier_entries for select
  using (true);

-- Seed data — Mythic+
insert into public.tier_entries (spec_id, content_type, rank, score, notes) values
  ('augmentation_evoker',  'mythic_plus', 'S', 99, 'Irreplaceable raid/M+ support'),
  ('fire_mage',            'mythic_plus', 'S', 97, 'Exceptional burst + utility'),
  ('subtlety_rogue',       'mythic_plus', 'S', 95, 'Shroud + massive single target'),
  ('windwalker_monk',      'mythic_plus', 'S', 93, 'Great burst + Ring of Peace'),
  ('discipline_priest',    'mythic_plus', 'S', 91, 'Best M+ healer currently'),
  ('havoc_dh',             'mythic_plus', 'A', 88, null),
  ('affliction_warlock',   'mythic_plus', 'A', 86, null),
  ('balance_druid',        'mythic_plus', 'A', 84, null),
  ('restoration_druid',    'mythic_plus', 'A', 82, null),
  ('vengeance_dh',         'mythic_plus', 'A', 81, null),
  ('marksmanship_hunter',  'mythic_plus', 'A', 80, null),
  ('shadow_priest',        'mythic_plus', 'A', 78, null),
  ('unholy_dk',            'mythic_plus', 'B', 75, null),
  ('frost_dk',             'mythic_plus', 'B', 73, null),
  ('arcane_mage',          'mythic_plus', 'B', 72, null),
  ('holy_paladin',         'mythic_plus', 'B', 70, null),
  ('protection_paladin',   'mythic_plus', 'B', 69, null),
  ('mistweaver_monk',      'mythic_plus', 'B', 68, null),
  ('elemental_shaman',     'mythic_plus', 'B', 66, null),
  ('retribution_paladin',  'mythic_plus', 'B', 65, null),
  ('outlaw_rogue',         'mythic_plus', 'B', 63, null),
  ('assassination_rogue',  'mythic_plus', 'B', 62, null),
  ('beast_mastery_hunter', 'mythic_plus', 'C', 58, null),
  ('frost_mage',           'mythic_plus', 'C', 56, null),
  ('arms_warrior',         'mythic_plus', 'C', 54, null),
  ('fury_warrior',         'mythic_plus', 'C', 53, null),
  ('enhancement_shaman',   'mythic_plus', 'C', 51, null),
  ('brewmaster_monk',      'mythic_plus', 'C', 50, null),
  ('guardian_druid',       'mythic_plus', 'C', 48, null),
  ('restoration_shaman',   'mythic_plus', 'C', 47, null),
  ('demonology_warlock',   'mythic_plus', 'C', 45, null),
  ('destruction_warlock',  'mythic_plus', 'D', 38, null),
  ('blood_dk',             'mythic_plus', 'D', 36, null),
  ('protection_warrior',   'mythic_plus', 'D', 35, null),
  ('feral_druid',          'mythic_plus', 'D', 34, null),
  ('survival_hunter',      'mythic_plus', 'D', 32, null),
  ('devastation_evoker',   'mythic_plus', 'D', 30, null),
  ('preservation_evoker',  'mythic_plus', 'D', 28, null),
  ('holy_priest',          'mythic_plus', 'D', 26, null)
on conflict (spec_id, content_type) do nothing;

-- Seed data — Raid
insert into public.tier_entries (spec_id, content_type, rank, score, notes) values
  ('augmentation_evoker',  'raid', 'S', 99, 'Must-have raid buff'),
  ('discipline_priest',    'raid', 'S', 96, 'Atonement healing dominates'),
  ('shadow_priest',        'raid', 'S', 94, null),
  ('fire_mage',            'raid', 'S', 92, null),
  ('affliction_warlock',   'raid', 'A', 89, null),
  ('balance_druid',        'raid', 'A', 87, null),
  ('restoration_druid',    'raid', 'A', 85, null),
  ('holy_paladin',         'raid', 'A', 83, null),
  ('windwalker_monk',      'raid', 'A', 81, null),
  ('havoc_dh',             'raid', 'A', 79, null),
  ('unholy_dk',            'raid', 'A', 77, null),
  ('elemental_shaman',     'raid', 'B', 74, null),
  ('marksmanship_hunter',  'raid', 'B', 72, null),
  ('mistweaver_monk',      'raid', 'B', 70, null),
  ('retribution_paladin',  'raid', 'B', 68, null),
  ('arcane_mage',          'raid', 'B', 66, null),
  ('demonology_warlock',   'raid', 'B', 64, null),
  ('restoration_shaman',   'raid', 'B', 62, null),
  ('subtlety_rogue',       'raid', 'C', 57, null),
  ('outlaw_rogue',         'raid', 'C', 55, null),
  ('assassination_rogue',  'raid', 'C', 53, null),
  ('arms_warrior',         'raid', 'C', 51, null),
  ('fury_warrior',         'raid', 'C', 49, null),
  ('frost_mage',           'raid', 'C', 47, null),
  ('preservation_evoker',  'raid', 'C', 45, null),
  ('vengeance_dh',         'raid', 'C', 43, null),
  ('blood_dk',             'raid', 'D', 38, null),
  ('protection_paladin',   'raid', 'D', 36, null),
  ('guardian_druid',       'raid', 'D', 34, null),
  ('brewmaster_monk',      'raid', 'D', 32, null),
  ('protection_warrior',   'raid', 'D', 30, null),
  ('devastation_evoker',   'raid', 'D', 28, null),
  ('beast_mastery_hunter', 'raid', 'D', 26, null),
  ('feral_druid',          'raid', 'D', 24, null),
  ('enhancement_shaman',   'raid', 'D', 22, null),
  ('frost_dk',             'raid', 'D', 20, null),
  ('survival_hunter',      'raid', 'D', 18, null),
  ('destruction_warlock',  'raid', 'D', 16, null),
  ('holy_priest',          'raid', 'D', 14, null)
on conflict (spec_id, content_type) do nothing;

-- Seed data — PvP
insert into public.tier_entries (spec_id, content_type, rank, score, notes) values
  ('subtlety_rogue',       'pvp', 'S', 98, null),
  ('havoc_dh',             'pvp', 'S', 95, null),
  ('retribution_paladin',  'pvp', 'S', 93, null),
  ('shadow_priest',        'pvp', 'S', 91, null),
  ('frost_mage',           'pvp', 'A', 87, null),
  ('windwalker_monk',      'pvp', 'A', 85, null),
  ('holy_paladin',         'pvp', 'A', 83, null),
  ('fire_mage',            'pvp', 'A', 81, null),
  ('unholy_dk',            'pvp', 'A', 79, null),
  ('discipline_priest',    'pvp', 'A', 77, null),
  ('arms_warrior',         'pvp', 'B', 73, null),
  ('fury_warrior',         'pvp', 'B', 71, null),
  ('affliction_warlock',   'pvp', 'B', 69, null),
  ('feral_druid',          'pvp', 'B', 67, null),
  ('enhancement_shaman',   'pvp', 'B', 65, null),
  ('restoration_druid',    'pvp', 'B', 63, null),
  ('assassination_rogue',  'pvp', 'B', 61, null),
  ('outlaw_rogue',         'pvp', 'C', 56, null),
  ('demonology_warlock',   'pvp', 'C', 54, null),
  ('balance_druid',        'pvp', 'C', 52, null),
  ('elemental_shaman',     'pvp', 'C', 50, null),
  ('mistweaver_monk',      'pvp', 'C', 48, null),
  ('frost_dk',             'pvp', 'C', 46, null),
  ('marksmanship_hunter',  'pvp', 'C', 44, null),
  ('restoration_shaman',   'pvp', 'C', 42, null),
  ('destruction_warlock',  'pvp', 'D', 37, null),
  ('beast_mastery_hunter', 'pvp', 'D', 35, null),
  ('arcane_mage',          'pvp', 'D', 33, null),
  ('devastation_evoker',   'pvp', 'D', 31, null),
  ('augmentation_evoker',  'pvp', 'D', 29, null),
  ('blood_dk',             'pvp', 'D', 27, null),
  ('vengeance_dh',         'pvp', 'D', 25, null),
  ('protection_paladin',   'pvp', 'D', 23, null),
  ('guardian_druid',       'pvp', 'D', 21, null),
  ('brewmaster_monk',      'pvp', 'D', 19, null),
  ('protection_warrior',   'pvp', 'D', 17, null),
  ('survival_hunter',      'pvp', 'D', 15, null),
  ('preservation_evoker',  'pvp', 'D', 13, null),
  ('holy_priest',          'pvp', 'D', 11, null)
on conflict (spec_id, content_type) do nothing;
